// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "soberkoder@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/brokers": {
            "get": {
                "description": "Find brokers by code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Broker"
                ],
                "summary": "Find brokers",
                "parameters": [
                    {
                        "type": "string",
                        "name": "code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.BrokerResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/brokers/summaries": {
            "get": {
                "description": "Find broker summaries by stock code, start date, end date, investor type, and transaction type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Broker"
                ],
                "summary": "Find broker summaries",
                "parameters": [
                    {
                        "type": "string",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "ALL",
                            "F",
                            "F"
                        ],
                        "type": "string",
                        "name": "investor_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "stock_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "ALL",
                            "RG",
                            "TN",
                            "NG"
                        ],
                        "type": "string",
                        "name": "transaction_type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.BrokerSummaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/financial_report": {
            "get": {
                "description": "Find financial report by stock code, report period, and report year",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FinancialReport"
                ],
                "summary": "Find financial report",
                "parameters": [
                    {
                        "enum": [
                            "TW1",
                            "TW2",
                            "TW3",
                            "Audit"
                        ],
                        "type": "string",
                        "name": "report_period",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "report_year",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "stock_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.FinancialReportResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/stock": {
            "get": {
                "description": "Find stock by stock code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stock"
                ],
                "summary": "Find stock by stock code",
                "parameters": [
                    {
                        "type": "string",
                        "name": "stock_code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.StockResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/stock/summaries": {
            "get": {
                "description": "Find stock summaries by stock code, start date, and end date",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stock"
                ],
                "summary": "Find stock summaries",
                "parameters": [
                    {
                        "type": "string",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "stock_code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StockSummaryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/stocks": {
            "get": {
                "description": "List all stocks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stock"
                ],
                "summary": "List all stocks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StockResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Health check",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Attachment": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "string"
                },
                "file_modified": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_type": {
                    "type": "string"
                },
                "report_period": {
                    "type": "string"
                },
                "report_type": {
                    "type": "string"
                },
                "report_year": {
                    "type": "string"
                },
                "stock_code": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                }
            }
        },
        "model.AuditCommittee": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "model.BrokerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.BrokerSummaryData": {
            "type": "object",
            "properties": {
                "avg": {
                    "type": "number"
                },
                "broker_code": {
                    "type": "string"
                },
                "lot": {
                    "type": "number"
                },
                "val": {
                    "type": "string"
                }
            }
        },
        "model.BrokerSummaryResponse": {
            "type": "object",
            "properties": {
                "buyers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BrokerSummaryData"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "sellers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BrokerSummaryData"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "stock_code": {
                    "type": "string"
                },
                "summary": {
                    "$ref": "#/definitions/model.Summary"
                }
            }
        },
        "model.Commissioner": {
            "type": "object",
            "properties": {
                "is_independent": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "model.Director": {
            "type": "object",
            "properties": {
                "is_affiliated": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "model.Dividend": {
            "type": "object",
            "properties": {
                "cash_dividend_currency": {
                    "type": "string"
                },
                "cash_dividend_per_share": {
                    "type": "number"
                },
                "cash_dividend_per_share_currency": {
                    "type": "string"
                },
                "cash_dividend_total": {
                    "type": "number"
                },
                "cum_date": {
                    "type": "string"
                },
                "ex_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "payment_date": {
                    "type": "string"
                },
                "ratio_1": {
                    "type": "integer"
                },
                "ratio_2": {
                    "type": "integer"
                },
                "record_date": {
                    "type": "string"
                },
                "total_stock_bonus": {
                    "type": "number"
                },
                "type": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "model.FinancialReportResponse": {
            "type": "object",
            "properties": {
                "attachment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Attachment"
                    }
                },
                "file_modified": {
                    "type": "string"
                },
                "report_period": {
                    "type": "string"
                },
                "report_year": {
                    "type": "string"
                },
                "stock_code": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                }
            }
        },
        "model.Profile": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "bae": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fax": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "listing_date": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "main_business": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "stock_code": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                },
                "sub_industry": {
                    "type": "string"
                },
                "sub_sector": {
                    "type": "string"
                },
                "tin": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "model.Secretary": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fax": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "model.Shareholder": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "is_controller": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                },
                "share": {
                    "type": "number"
                }
            }
        },
        "model.StockResponse": {
            "type": "object",
            "properties": {
                "audit_committees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AuditCommittee"
                    }
                },
                "board": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "commissioners": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Commissioner"
                    }
                },
                "directors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Director"
                    }
                },
                "dividends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Dividend"
                    }
                },
                "listing_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "profiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Profile"
                    }
                },
                "secretaries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Secretary"
                    }
                },
                "share": {
                    "type": "number"
                },
                "shareholders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Shareholder"
                    }
                },
                "subsidiaries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Subsidiary"
                    }
                }
            }
        },
        "model.StockSummaryResponse": {
            "type": "object",
            "properties": {
                "bid": {
                    "type": "number"
                },
                "bid_volume": {
                    "type": "number"
                },
                "change": {
                    "type": "number"
                },
                "close": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "delisting_date": {
                    "type": "string"
                },
                "first_trade": {
                    "type": "number"
                },
                "foreign_buy": {
                    "type": "number"
                },
                "foreign_sell": {
                    "type": "number"
                },
                "frequency": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "id_stock_summary": {
                    "type": "integer"
                },
                "index_individual": {
                    "type": "number"
                },
                "listed_shares": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "non_regular_frequency": {
                    "type": "number"
                },
                "non_regular_value": {
                    "type": "number"
                },
                "non_regular_volume": {
                    "type": "number"
                },
                "offer": {
                    "type": "number"
                },
                "offer_volume": {
                    "type": "number"
                },
                "open_price": {
                    "type": "number"
                },
                "percentage": {},
                "persen": {},
                "previous": {
                    "type": "number"
                },
                "remarks": {
                    "type": "string"
                },
                "stock_code": {
                    "type": "string"
                },
                "stock_name": {
                    "type": "string"
                },
                "tradeble_shares": {
                    "type": "number"
                },
                "value": {
                    "type": "number"
                },
                "volume": {
                    "type": "number"
                },
                "weight_for_index": {
                    "type": "number"
                }
            }
        },
        "model.Subsidiary": {
            "type": "object",
            "properties": {
                "business_fields": {
                    "type": "string"
                },
                "commercial_year": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "operation_status": {
                    "type": "string"
                },
                "percentage": {
                    "type": "number"
                },
                "total_asset": {
                    "type": "number"
                },
                "units": {
                    "type": "string"
                }
            }
        },
        "model.Summary": {
            "type": "object",
            "properties": {
                "avg": {
                    "type": "number"
                },
                "foreign_net_val": {
                    "type": "string"
                },
                "total_lot": {
                    "type": "number"
                },
                "total_val": {
                    "type": "string"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go Stock API",
	Description:      "This is a simple API for stock data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
